#!/usr/bin/env python3
"""Wrapper: page-level CMS actions are generated by build_query_workbench_bundle.py in v5."""
import json
print(json.dumps({'status':'delegated','message':'Run scripts/build_query_workbench_bundle.py to generate page_level_cms_recommendations and CMS actions.'}, indent=2))
