#!/usr/bin/env python3
"""Wrapper: grouped PR opportunities are generated by build_query_workbench_bundle.py in v5."""
import json
print(json.dumps({'status':'delegated','message':'Run scripts/build_query_workbench_bundle.py to generate grouped_pr_opportunities and PR actions.'}, indent=2))
